version: '3'
services:
  server:
    build: ./
    ports:
      - 8080:8080

  db:
    image: postgres
    ports:
      - "5436:5432"
    volumes:
    - ./.database/postgresql/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: wb_user
      POSTGRES_PASSWORD: 3636
      POSTGRES_DB: wildberries
  