env: "local" # Окружение - local, dev или prod
rest_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 30s
postgres:
  host: "localhost"
  port: "5436"
  user: "wb_user"
  password: "3636"
  dbname: "wildberries"