env: "local" # Окружение - local, dev или prod
rest_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 30s
postgres:
  host: "postgresql"
  port: "5432"
  user: "wb_user"
  password: "3636"
  dbname: "wildberries"
nats-streaming:
  host: "nats-streaming"
  port: "4222"
  cluster: "cluster1"
  subject_order_add: "order.add"