env: "local" # Окружение - local, dev или prod
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 30s
schedule_storage:
  host: "localhost"
  port: "5432"
  user: "wb_user"
  password: "3636"
  dbname: "wildberries"